### ISSUE TITLE
Broken pronunciation button styling (mdict)

### ISSUE THREAD

**Issue by epistularum** [stephenmk/Jitendex#100]
Jitendex v. 2024-06-24
goldendict-ng v 24.05.05

The styling for the pronunciation button is broken in the mdict version.

![image](https://github.com/stephenmk/Jitendex/assets/34507493/380ab480-6027-450f-8798-881137b0ad7e)

**Comment by stephenmk** [comment]
The current style I'm using produces a differently shaped oval depending on the font that's being used. I think the problem has something to do with the inherent line height of a given font, but I'm not sure.

I've started using a `clip-path: circle();` style instead whenever I need to render circular icons. This style produces a perfect circle regardless of the font. I forgot to fix the audio button here, so thanks for letting me know.

If you want to edit your local copy of the `jitendex.css` stylesheet, this class should make it look a little nicer. It won't look exactly the same because I'm not sure how to achieve the same appearance as the old style using only CSS. I think I'd probably need to replace it with an embedded SVG image.

``` css
.play-button {
    margin-right: 0.5em;
    display: inline-block;
    background: radial-gradient(white, silver);
    padding: 0em 0.15em 0em 0.25em;
    clip-path: circle();
}
```

![button](https://github.com/stephenmk/Jitendex/assets/8003332/0c9df4f4-6dd9-49a2-90f8-ab405c6ed22d)
