### ISSUE TITLE
Add color-coding styles to forms table headers

### ISSUE THREAD

**Issue by stephenmk** [stephenmk/Jitendex#115]
Just an idea. I chose the colors at random for the purposes of a mockup and they're certainly not final.

![mockup](https://github.com/user-attachments/assets/1c40f056-9450-458e-92ed-7d8322a0ae28)

The diagonal line effect can be implemented by a `background` style.

```css
.top-left-th {
  background: linear-gradient(to top right, color1 49%, black 50%, color2 51%)
}
```
